name: Testsite
favicon: null
layout_spectrum: 0.4299877267330885
typography_spectrum: 0.22445472609251738
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.33994977874681354
  lightness: 0.7003780577797443
  saturation: 0.8307932906318456
  rhythmicContrast: 0.038743869634345174
purpose: []
